### ISSUE TITLE
Build Event Summary View

### ISSUE THREAD

**Issue by jpatton-USGS** [usgs/hydra-web-display#4]
Should Contain 
* Preferred Latitude 
* Preferred Longitude
* Preferred Origin Time
* Preferred Depth
* Preferred Magnitude
* Preferred Magnitude Type

**Comment by emartinez-usgs** [comment]
- Pay attention to vertical whitespace regarding coding standards.
- In general, do not use `<b>` tags. Prefer `<strong>` tags, however ...
- I suggest the following markup for each item in the summary:
```html
<label class="event-summary-label" for="event-summary-origin-time">OT</label>
<span class="event-summary-value" id="event-summary-origin-time">
  2016-07-19T05:18:38:58Z
</span>
```
And similar for each item. This creates a strong key-value association. Additionally, you should add CSS so the values do not wrap at word-breaks:
```css
.event-summary-value {
  white-space: nowrap;
}
```
- Remove unnecessary CSS from index.scss that was a placeholder until this view/css was actually implemented.
- Add method comments to primary view class.

**Comment by emartinez-usgs** [comment]
On smaller screens, add CSS so the stacked key-value pairs have a clean left edge on the values.

**Comment by emartinez-usgs** [comment]
Include the "Time Since" field in this. It should count up as elapsed time since preferred origin time. Use formatting for longer time frames like "1 week 3 days 11:23: 44".
