### ISSUE TITLE
MagnitudeSummaryView

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/hydra-web-display#5]
This view is the panel content in the "Summary" tab on the MagnitudeDisplay. It should render the primary key-value pairs for magnitude information as well as a beachball (if a tensor is available). The view should also contain a MagnitudeCollectionView at the bottom which will contain only magnitudes of the same type as the current magnitude that are also for the current event.

If the rendered magnitude does not contain a particular value, that value field should render blank, but the key should still be listed. Possibly use a description list or table for layout for key-value pairs.

**Comment by emartinez-usgs** [comment]
Needs rebase.

#12 is complete now, so this should be able to move forward.

**Comment by emartinez-usgs** [comment]
Talked with @jpatton-USGS :

- %CLVD = 1 - %DC
- We should remove the `Mw'` and the `Weight` fields
- @jpatton-USGS still needs to provide `Solution Method`. Leave it blank for now.
- Source Time should be split into three component fields. `decay`, `duration`, `rise`, and should all be labeled as `source time`...
