### ISSUE TITLE
Create Magnitude Collection View

### ISSUE THREAD

**Issue by jpatton-USGS** [usgs/hydra-web-display#6]
List of all magnitudes for an Event, contains:
* Magnitude Value
* Magnitude Type
* Source (Author/Inst)?

**Comment by emartinez-usgs** [comment]
- MagnitudeCollectionTable should not attempt to open the MagnitudeDisplay. This view will be used in different contexts and opening the MagnitudeDisplay is not always appropriate.
- Pay attention to vertical white spacing.
- Prefer binding by function name when available (MVC events). Only use the private/public event binding for DOM events.
- Perhaps view should highlight selected magnitude.
- I don't see the "installation" property listed.

*Question*: Should we include the HUID here?
